apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: authorities-management
  name: authorities-management
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: authorities-management
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authorities-management
    spec:
      containers:
        - name: authorities-management
          resources:
            requests:
              ephemeral-storage: 1Gi
            limits:
              ephemeral-storage: 1Gi
