quarkus:
  datasource:
    db-kind: postgresql
    username: user
    password: password
    jdbc:
      url: jdbc:postgresql://localhost:5432/forschungsdaten
      min-size: 3
      max-size: 13
  container-image:
    build: true
    push: true
    group: wwuulb
    name: marc-authority-editor
    registry: ulb.wwu.io
  http:
    auth:
      permission:
        authenticated:
          paths: /xhtml/*
          policy: authenticated
    proxy:
      proxy-address-forwarding: true
  oidc:
    auth-server-url: https://oidc-server
    client-id: pacelli-gnd-marc-editor
    application-type: web_app
    credentials:
      client-secret:
        value: diesistgeheim
        method: basic
    roles:
      roles:
        source: userinfo
    tls:
      verification: none
    authentication:
      scopes: [email, account, profile]
      force-redirect-https-scheme: true
      redirect-path: /xhtml/index.xhtml
      restore-path-after-redirect: false
      user-info-required: true
  kubernetes:
    image-pull-secrets: ulbreg
    mounts:
      tls-certs:
        path: /tls
        read-only: true
      postgres-certs:
        path: /opt/.postgresql
        read-only: true
    secret-volumes:
      tls-certs:
        secret-name: authority-tls
      postgres-certs:
        secret-name: postgres-tls
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 2
        memory: 2Gi
  kubernetes-config:
    enabled: true
    fail-on-missing-config: false
    config-maps: mae-cm
    secrets:
      ~: mae-secret
      enabled: true
  log:
    level: INFO

de:
  wwu:
    ulb:
      mae:
        client:
          AuthoritySruSearchClient/mp-rest/url: http://authorities-management:8080/authorities-management-service/api/v1/retrieve
          AuthoritySruUpdateClient/mp-rest/url: http://authorities-management:8080/authorities-management-service/api/v1/record
        tablename: pacelli
        firstnamecolumn: firstname
        lastnamecolumn: lastname
        marccolumn: marc21
        idcolumn: pacelliid
        gndidcolumn: gndid
        gndupdatedcolumn: gndupdated
        removedgndidcolumn: removedgndid
        pngndidcolumn: pngndid
        gndlevelcolumn: gndlevel
        notescolumn: notes
      authorities:
        pk: /tls/privateKey.pem
