quarkus:
  datasource:
    db-kind: postgresql
    username: user
    password: password
    jdbc:
      url: jdbc:postgresql://localhost:5432/forschungsdaten
      min-size: 3
      max-size: 5
      initial-size: 3
  container-image:
    build: true
    push: true
    group: wwuulb
    name: marc-authority-editor
    registry: ulb.wwu.io
  http:
    non-application-root-path: /authority-editor/q
    port: 8080
    auth:
      permission:
        authenticated:
          paths: /xhtml/*
          policy: authenticated
      basic: true
    proxy:
      proxy-address-forwarding: true
  smallrye-health:
    root-path: health
    ui:
      always-include: true
  oidc:
    enabled: false
    auth-server-url: https://oidc-server
    client-id: pacelli-gnd-marc-editor
    application-type: web-app
    tenant-enabled: true
    credentials:
      client-secret:
        value: diesistgeheim
        method: basic
      jwt:
        token-key-id: pacelli
    roles:
      source: userinfo
    tls:
      verification: none
    authentication:
      scopes: email, account
      force-redirect-https-scheme: true
      redirect-path: /xhtml/index.xhtml
      restore-path-after-redirect: false
      user-info-required: true
  security:
    ldap:
      enabled: true
      dir-context:
        principal: ulbdzal@wwu
        url: ldap://wwu.de
        password: xyz
      identity-mapping:
        rdn-identifier: cn
        search-base-dn: ou=Projekt-Benutzer,dc=wwu,dc=de
        attribute-mappings:
          "0":
            from: cn
            to: groups
            filter: (member=cn={0})
            filter-base-dn: ou=Projekt-Gruppen,dc=wwu,dc=de
  kubernetes:
    image-pull-secrets: ulbreg
    mounts:
      tls-certs:
        path: /tls
        read-only: false
      postgres-certs:
        path: /opt/.postgresql
        read-only: false
    secret-volumes:
      tls-certs:
        secret-name: authority-tls
        default-mode: 0666
      postgres-certs:
        secret-name: postgres-tls
        default-mode: 0666
    resources:
      limits:
        cpu: 0.5
        memory: 2Gi
      requests:
        cpu: 0.5
        memory: 2Gi
    add-version-to-label-selectors: false
  kubernetes-config:
    enabled: true
    fail-on-missing-config: false
    config-maps: mae-cm
    secrets:
      ~: mae-secret
      enabled: true
  log:
    level: INFO

de:
  wwu:
    ulb:
      authorities-search-service:
        ssl: false
        host: authorities-management
        port: 80
        query: /authorities-management-service/api/v1/retrieve/search
      authorities-update-service:
        ssl: false
        host: authorities-management
        port: 80
        create: /authorities-management-service/api/v1/record/create
        update: /authorities-management-service/api/v1/record/update
      mae:
        oidc: satosa
        client:
          AuthoritySruSearchClient/mp-rest/url: http://authorities-management:8080/authorities-management-service/api/v1/retrieve
          AuthoritySruSearchClient/mp-rest/scope: javax.inject.Singleton
          AuthoritySruUpdateClient/mp-rest/url: http://authorities-management:8080/authorities-management-service/api/v1/record
        tablename: pacelli
        firstnamecolumn: firstname
        lastnamecolumn: lastname
        marccolumn: marc21
        idcolumn: pacelliid
        gndidcolumn: gndid
        gndupdatedcolumn: gndupdated
        removedgndidcolumn: removedgndid
        pngndidcolumn: pngndid
        gndlevelcolumn: gndlevel
        notescolumn: notes
      authorities:
        pk: /tls/privateKey.pem
