quarkus:
  datasource:
    db-kind: postgresql
    username: user
    password: password
    jdbc:
      url: jdbc:postgresql://localhost:5432/forschungsdaten
      min-size: 3
      max-size: 13
  log:
    level: INFO
