apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: pacelli-editor-policy
  namespace: pacelli-editor
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: marc-authority-editor
  ingress:
    - fromEndpoints:
        - {}
    - fromEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
    - fromEndpoints:
        - matchLabels:
            io.cilium.k8s.policy.cluster: ms1
            k8s:app: istio-ingressgateway
            k8s:io.kubernetes.pod.namespace: istio-ingressgateway
            k8s:istio: ingressgateway
            k8s:name: istio-ingressgateway
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: authorities-management
      toPorts:
        - ports:
            - port: "8080"
    - toFQDNs:
        - matchPattern: "*.uni-muenster.de"
      toPorts:
        - ports:
            - port: "54331"
    - toFQDNs:
        - matchPattern: "*.k8s.wwu.de"
      toPorts:
        - ports:
            - port: "443"
