apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: workshop
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  # commonName and dnsNames are restricted and need to be apply for in the
  # project application, if the wwuit-acme cluster issuer is used.
  commonName: "kubernetes-workshop.uni-muenster.de"
  dnsNames:
    - "kubernetes-workshop.uni-muenster.de"
    - "kubernetes-workshop.wwu.de"
  # Cluster Issuer with which certificates from the DFN can be requested.
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: wwuit-acme
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 256
  secretName: workshop-certificate
  subject:
    countries:
      - DE
    provinces:
      - Nordrhein-Westfalen
    localities:
      - Muenster
    organizations:
      - Westfaelische Wilhelms-Universitaet Muenster
